### ISSUE TITLE
Upgrade edx-exams to Django 4.2

### ISSUE THREAD

**Issue by iamsobanjaved** [edx/edx-exams#173]
```[tasklist]
### Tasks
- [x] Add `USE_DEPRECATED_PYTZ` to the settings, also add `pytz` to `base.in` if not there already. (more info: https://docs.djangoproject.com/en/4.2/releases/4.0/#zoneinfo-default-timezone-implementation)
- [x] Override common constraint of Django
- [x] Run make upgrade with Django 4.2
- [x] Drop testing of Django 3.2
- [ ] Inform the owning team about the change in the hashing algorithm (More info: https://github.com/edx/edx-arch-experiments/issues/453)
```
